#Log level
log_level = "info"
elastic_address = "localhost"
elastic_port = 9200
elastic_index = "quiz_registrator_api_prod"
elastic_logs_enabled = true

#
# ics manager settings
#
bind_address = "localhost"
bind_port = 8082
ics_file_extension = ".ics"
ics_files_folder = "/var/www/quiz/ics/"
rabbitmq_address = "localhost"
rabbitmq_ics_queue_name = "quiz_ics_prod"
rabbitmq_port = 5672
rabbitmq_username = "quiz_reminder"
registrator_api_address = "localhost"
registrator_api_port = 8080

#
# DB Settings
#
driver = "mysql"
database_address = "localhost"
database_name = "quiz_ics_manager_api_prod"
database_port = 3306
database_username = "quiz_prod"
