[apiserver]
  [apiserver.bind]
  address = "0.0.0.0"
  port = 8082

[database]
address = "database"
dbname = "ics_manager_api"
driver = "mysql"
port = 3306
  [database.credentials]
  username = "quiz_regbot"
  password = "TOPSECRET"

[ics_consumer]
ics_file_extension = ".ics"
ics_files_folder = "/var/www/quiz/ics/"
  [ics_consumer.rabbitmq]
  address = "rabbitmq"
  port = 5672
    [ics_consumer.rabbitmq.credentials]
    username = "quiz_regbot"
    password = "TOPSECRET"
    [ics_consumer.rabbitmq.queue]
    name = "ics"
  [ics_consumer.registrator_api]
  address = "registrator-api"
  port = 8082

[log]
level = "info"
module_name = "ics-manager"
  [log.elastic]
  address = "elasticsearch"
  enabled = true
  index = "quiz_regbot"
  port = 9200