version: "3.9"

services:
  ics-manager-api:
    build:
      args:
        BASE_IMAGE: ${BASE_IMAGE}
      context: .
      dockerfile: Dockerfile
    command: "/bin/ics-manager-api --config /etc/config.toml"
    container_name: ics-manager-api
    env_file:
      - path: .env
        required: true
    networks:
      - network
    volumes:
      - icsdata:/var/www/quiz/ics/

volumes:
  icsdata:
    driver: local

networks:
  network:
    driver: bridge
